spring:
  r2dbc:
    url: r2dbc:mysql://mydatabase.ccgvbsnacswx.sa-east-1.rds.amazonaws.com:3306/amazonTest?zeroDateTimeBehavior=convertToNull&useSSL=false&useServerPrepareStatement=true
    username: admin
    password: superbowser

  data:
    jpa:
      repositories:
        enabled: true
      database-platform=org:
        hibernate:
          dialect:
            MySQL8Dialect:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: mysql
